# Generated by Django 5.2.7 on 2025-10-18 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(db_index=True)),
                ("end", models.DateTimeField()),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning"),
                            ("checkup", "Checkup"),
                            ("filling", "Filling"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["appointment_type", "start"],
                        name="appointment_appoint_ea3560_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=32)),
                ("dob", models.DateField()),
                (
                    "insurance_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["phone"], name="appointment_phone_d46677_idx"),
                    models.Index(
                        fields=["full_name"], name="appointment_full_na_ee1dcf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning"),
                            ("checkup", "Checkup"),
                            ("filling", "Filling"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=24,
                    ),
                ),
                ("start", models.DateTimeField(db_index=True)),
                ("end", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("canceled", "Canceled"),
                            ("completed", "Completed"),
                        ],
                        default="booked",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="appointments.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("emergency", "Emergency"), ("general", "General")],
                        default="general",
                        max_length=24,
                    ),
                ),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("other", "Other"),
                        ],
                        default="self",
                        max_length=16,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="appointments.family",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="families",
                        to="appointments.patient",
                    ),
                ),
            ],
            options={
                "unique_together": {("family", "patient")},
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "start"], name="appointment_patient_de3304_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("patient", "start", "end"), name="uniq_patient_timeslot"
            ),
        ),
        migrations.AddIndex(
            model_name="staffalert",
            index=models.Index(
                fields=["kind", "created_at"], name="appointment_kind_f8438b_idx"
            ),
        ),
    ]
